issuer: "https://dev-87508909.okta.com/oauth2/default"
client_id: "0oa17ukekngEqWKil5d7"
audience: "api://default"

db_uri: "mongodb://localhost:27017"
db_name: "c18n"

# custom JWT tokens for dummy users.
algo: "HS256"
secret_key: "AQuickBrownFoxJumpsOverTheLazyDog"

token_expiry_in_days: 7

kafka_endpoint: "localhost:9092"
zookeeper_endpoint: "localhost:2181"

default_per_page: 10
max_per_page: 100

