speed:
  batch_interval: 5
  name: 'speed'
  checkpoint_dir: 'var/data/spark/speed'
  log_dir: 'var/data/spark/speed/logs'

batch:
  batch_interval: 60
  name: 'batch'
  checkpoint_dir: 'var/data/spark/batch'
  log_dir: 'var/data/spark/batch/logs'

source:
  name: 'kafka'
  host:: 'localhost'
  port: 9092

sink:
  name: 'elasticsearch'
  host: 'localhost'
  port: 9200

topics:
  users:
    fields:
    - id
    - name
    - creation_date
    - action
  communities:
    fields:
    - id
    - name
    - created_by
    - creation_date
    - tags
    - action
  usergroups:
    fields:
    - id
    - name
    - community_id
    - created_by
    - creation_date
    - tags
    - action
  posts:
    fields:
    - id
    - community_id
    - usergroup_id
    - created_by
    - content
    - creation_date
    - action
  images:
    fields:
    - id
    - community_id
    - usergroup_id
    - created_by
    - name
    - creation_date
    - action
  videos:
    fields:
    - id
    - community_id
    - usergroup_id
    - created_by
    - name
    - creation_date
    - action
  invites:
    fields:
    - id
    - community_id
    - invite_by
    - invite_to
    - creation_date
    - action
  subscribes:
    fields:
    - id
    - community_id
    - subscribe_by
    - creation_date
    - action
