speed:
  num_threads: 2
  batch_interval: 1
  name: 'speed'
  source_host: "localhost"
  source_port: 9092
  source_type: 'kafka'

batch:
  num_threads: 2
  batch_interval: 30
  name: 'batch'
  source_host: "localhost"
  source_port: 27087
  source_type: 'mongo'

sink:
  doc_type: 'elasticsearch'
  index: 1
  host: 'localhost'
  port: 9093